
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 03 04:37:53 EST 2003
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Calc2Symbol {
  /* terminals */
  public static final int MULTI = 7;
  public static final int NUMBER = 8;
  public static final int SEMI = 5;
  public static final int EQUAL = 4;
  public static final int EOF = 0;
  public static final int PLUS = 6;
  public static final int ID = 9;
  public static final int error = 1;
  public static final int RPAREN = 3;
  public static final int LPAREN = 2;

}